import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/components/navigation/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localWanted = localFont({
  src: "../fonts/WantedSans-Bold.woff2",
  variable: "--wanted-bold-text",
});

export default function NavLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      <div className="h-full mx-auto w-full">{children}</div>
    </>
  );
}
