import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        {/* <div className="mx-auto my-0 w-[390px] h-full">{children}</div> */}
        <div className="w-full h-full mx-auto max-w-[430px]">{children}</div>
      </body>
    </html>
  );
}
